### ISSUE TITLE
UBS Banking app test

### ISSUE THREAD

**Issue by mikispag** [stapelberg/qrbill#3]
# Donation

Prefills Legalize it! with account *3543 without any amount and reason "Spende 420".

# Invoice

Prefills Legalize it! with account *3543 with an amount of 23.42 CHF and reason "Spende 420".

# Invoice without amount

Prefills Legalize it! with account *3543 without any amount and reason "Spende 420".

**Comment by stapelberg** [comment]
Thanks very much! Could you repeat with the codes of v0.1.4 please? https://github.com/stapelberg/qrbill#qrbill-v014-2020-sep-21

**Comment by metebalci** [comment]
I also just tested with UBS on iOS and the result is the same as above both for v1.0.3 and v1.0.4 codes.

**Comment by stapelberg** [comment]
Great, thanks! @mikispag did you test with iOS as well, or Android?

**Comment by juergbi** [comment]
The same result with UBS on Android for v0.1.4. The sender "Mary Jane" is picked up as well for the two invoice codes as "Invoice recipient".

**Comment by stapelberg** [comment]
@juergbi Thanks, now added, too!
